---
  - hosts: all
    remote_user: ubuntu
    become: true
    gather_facts: no
    ignore_errors: true
    tasks: 
      - name: apt package update
        shell: apt update
      - name: Install apache package
        apt:
          name: apache2 
          state: present
      - name: Copy file with owner & permissions
        copy:
          src: mywebsite.html
          dest: /var/www/html/
          owner: ubuntu
          group: root
          mode: '0777'
      - name: Start apache service
        service: 
          name: apache2
          state: started
