---
  - hosts: all
    remote_user: ubuntu
    become: true
    gather_facts: no
    ignore_errors: true
    tasks: 
      - name: Add Docker GPG apt Key
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present
      - name: Add Docker Repository
        apt_repository:
          repo: deb https://download.docker.com/linux/ubuntu bionic stable
          state: present
      - name: Update apt and install docker-ce
        apt: update_cache=yes name=docker-ce state=present
      - name: Create default containers
        docker_container:
          name: mywebserver
          image: httpd
          state: present
        with_sequence: count=1
