---
  - hosts: all
    remote_user: ubuntu
    become: true
    gather_facts: no
    ignore_errors: true
    tasks: 
      - name: Add Docker GPG apt Key
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present
      - name: Add Docker Repository
        apt_repository:
          repo: deb https://download.docker.com/linux/ubuntu bionic stable
          state: present
      - name: Update apt and install docker-ce
        apt: update_cache=yes name=docker-ce state=present
      - name: docker-compose install
        shell: curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - name: change docker-compose privilage
        shell: chmod +x /usr/local/bin/docker-compose
      - name: create link file
        shell: ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
      - name: compose file copy
        copy: 
          src: docker-compose.yml
          dest: /tmp
